spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/./guitarShop
#    url: jdbc:h2:mem:guitarShop
    url: jdbc:mysql://54.180.116.59/guitarShop
    username: sa
    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  h2:
    console:
      enable: true
      path: /h2.console

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 8080
  address: 0.0.0.0